# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ eqivablue ]
  pull_request:
    branches: [ eqivablue ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B install -f "bundles/org.openhab.binding.bluetooth.eqivablue/pom.xml"
    - uses: actions/upload-artifact@v2
      with:
        name: Eqivablue Binding
        path: /home/runner/.m2/repository/org/openhab/addons/bundles/org.openhab.binding.bluetooth.eqivablue/
